# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    container_name: bdd-mariaDB-10.7

  adminer:
    image: adminer
    container_name: adminerForMariaDB
    restart: always
    ports:
      - 8081:8080